title: Jaszium - About (SSJT)
description: |-
  A bold typographic theme inspired by Swiss design.
  Provided by Stastic Swiss Jekyll Theme (SSJT)
social_link: youtube
social_username: jaszium
github_repo: about
github_username: jaszium
theme_color: darkblue
remote_theme: internet-de-france/swiss
baseurl: /about
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
